### PR TITLE
Firebase Sender

### PR DESCRIPTION
**Pull request by zanahrastovsek**
Minor additions to make the Sender suitable for Firebase with no impact on legacy code.

If there is interest, the project could be properly refactored for Firebase (and legacy) support.

### CODE REVIEW

**Comment by zanahrastovsek** [comment]
I signed it!

**Comment by ogeidix** [comment]
Is it possible that you signed it with the wrong email?
The googlebot thinks that you didn't sign it

**Comment by zanahrastovsek** [comment]
I just checked, I definitely signed it. Not sure why googlebot hasn't picked it up.

**Comment by zanahrastovsek** [comment]
I double checked it now. If I click on the link you provided, I am notified that I have already signed a CLA for this email address, which is the same as the one I am using for my Github account.

**Comment by ogeidix** [comment]
For future reference:
git commits include the email address configured in the local git client.
Which can be different from the email address used by the github account.
see the message by @googlebot above.

**Comment by zanahrastovsek** [comment]
I was using another computer, so I see now how this could have happened. I created a new pull request now, by committing from my computer where I definitely have the right email set.

**Pull request closed without merging**
