### PR TITLE
Fix method name typo

### PR DESCRIPTION
**Pull request by russellpwirtz**
Change InstanceIdHelper method name in gcm demo from 'deleteGcmTokeInBackground' to 'deleteGcmTokenInBackground'

### CODE REVIEW

**Comment by russellpwirtz** [comment]
I signed it!

**Comment by silvolu** [comment]
@russellpwirtz I cannot find you in the list of signers of our CLA, have you signed the corporation CLA?

**Comment by russellpwirtz** [comment]
Yes I've signed it. I can do so again if need be.

**Comment by silvolu** [comment]
Can you see your agreement if you navigate to https://cla.developers.google.com/clas? Have you signed your agreement providing the email address associated to your github username?

**Comment by russellpwirtz** [comment]
I've resubmitted it just now, it said I already signed but I went ahead and
re-agreed.

**Comment by silvolu** [comment]
Oh I see, it looks like you signed the CLA for Android, but you need to sign the Google CLA to contribute to this project.

**Comment by kroikie** [comment]
@russellpwirtz did you have a chance to sign the Google CLA?

**Comment by russellpwirtz** [comment]
Yes I did, thanks.

**Comment by kroikie** [comment]
Thanks @russellpwirtz looks good.

**Comment by kroikie** [comment]
Hi @russellpwirtz could you rebase your PR to allow it to be merged.

**Comment by russellpwirtz** [comment]
It should be complete now, thanks.

**Comment by kroikie** [comment]
Hi @russellpwirtz there are still conflicts to be resolved.

**Comment by russellpwirtz** [comment]
Complete.

**Comment by kroikie** [comment]
Thanks for the PR @russellpwirtz but since the PR results in no changes there is no need to merge it.

**Comment by russellpwirtz** [comment]
Indeed. Good learning experience for me anyway.

**Pull request closed without merging**
